[tool.poetry]
name = "example"
version = "0.1.0"
package-mode = false
description = ""
authors = ["Grigory-Yunusov <grigoriyzawr@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
